<?php

namespace Capimichi\Instagram\Request;

use Capimichi\Instagram\InstagramSession;
use Unirest\Request;

/**
 * Class AuthenticatedRequest
 * @package Capimichi\Instagram\Request
 */
class AuthenticatedCachedRequest extends CachedRequest
{
    /**
     * @param string $url
     * @param int $expiration
     * @param array $headers
     * @param null $parameters
     * @param null $username
     * @param null $password
     * @return \Unirest\Response
     */
    public static function get($url, $expiration = 172800, $headers = array(), $parameters = null, $username = null, $password = null)
    {
        $headers = array_merge($headers, InstagramSession::getSessionHeaders());
        return parent::get($url, $expiration, $headers, $parameters, $username, $password); // TODO: Change the autogenerated stub
    }
}